export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const TRENDING_PRODUCTS_REQUEST = 'TRENDING_PRODUCTS_REQUEST';
export const TRENDING_PRODUCTS_SUCCESS = 'TRENDING_PRODUCTS_SUCCESS';
export const TRENDING_PRODUCTS_FAIL = 'TRENDING_PRODUCTS_FAIL';

export const PRODUCT_DETAIL_REQUEST = 'PRODUCT_DETAIL_REQUEST';
export const PRODUCT_DETAIL_SUCCESS = 'PRODUCT_DETAIL_SUCCESS';
export const PRODUCT_DETAIL_FAIL = 'PRODUCT_DETAIL_FAIL';