# Generated by Django 4.1.4 on 2023-05-07 22:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_order_product', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('quantity', models.IntegerField(default=1)),
                ('ordered', models.BooleanField(default=True)),
                ('price', models.FloatField(null=True)),
            ],
            options={
                'verbose_name': 'order product',
                'verbose_name_plural': 'order products',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid_order', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email', models.TextField(max_length=255, verbose_name='email address')),
                ('address', models.TextField()),
                ('city', models.TextField()),
                ('postal_code', models.CharField(max_length=100)),
                ('state', models.TextField()),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('ordered', models.BooleanField(default=True)),
                ('selected_coupon', models.CharField(blank=True, max_length=500, null=True)),
                ('total_price', models.FloatField(default=0)),
                ('order_status', models.CharField(choices=[('pending', 'Ne pritje'), ('confirmed', 'E konfirmuar'), ('finished', 'E perfunduar'), ('cancelled', 'Anuluar')], max_length=20)),
                ('payment_type', models.CharField(max_length=50)),
                ('additional_info', models.CharField(blank=True, max_length=2000, null=True)),
                ('products', models.ManyToManyField(to='orders.orderproduct')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
    ]
