# Generated by Django 4.1.4 on 2023-05-07 22:46

from django.db import migrations, models
import django.db.models.deletion
import products.blocks
import uuid
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('uuid_product', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', wagtail.fields.StreamField([('Image', wagtail.blocks.StructBlock([('image', products.blocks.ImageChooserBlock())]))], use_json_field=True)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.FloatField()),
                ('price_with_sale', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('shipping', models.CharField(blank=True, max_length=2000)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('brand', models.CharField(blank=True, max_length=200, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.categories')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
            bases=('wagtailcore.page',),
        ),
    ]
